### PR TITLE
Remove AWS SDKv2

### PR DESCRIPTION
**Pull request by Ic3w0lf**
## What it solves

* Replace any SDKv2 references and replace SmokeTail with SDKv3 native code
* Start the LogTail before the Container is in running state, so no more logs should be missing

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request
- [ ] Pull request title is brief and descriptive (for a changelog entry)

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, or `enhancement`
- [ ] Label as `bump:patch`, `bump:minor`, or `bump:major` if this PR should create a new release

### CODE REVIEW

**Comment by MrNoyceCosta** [comment]
@Ic3w0lf When will his be merged? I'm getting some odd timeout errors when running the 4.1.0 version and would like to check if this PR fixes the issue.

FYI ``` Error: Task did not stop successfully. Error: TimeoutError. State: undefined. ```

**Comment by Ic3w0lf** [comment]
Hey @MrNoyceCosta 

I still need to fix some issues regarding the action not outputting all logs. However, the error you get sounds like maybe your task runs longer than 5 minutes or takes more time to start up. Did you try increasing the `task-stopped-max-wait-time` from 300 to something higher? Alternatively, maybe try increasing the `task-start-max-wait-time` which controls how long the action will wait for the task to get to the **RUNNING** state.

Also, I think you can define branch names when you use this action. E.g. like `geekcell/github-action-aws-ecs-run-task@sdkv3-rep` or commit hashes.

Best regards

**Comment by MrNoyceCosta** [comment]
@Ic3w0lf Thanks for your reply. The task could be running for quite some time. What is the max value that can be set for task-stopped-max-wait-time?

**Comment by Ic3w0lf** [comment]
> @Ic3w0lf Thanks for your reply. The task could be running for quite some time. What is the max value that can be set for task-stopped-max-wait-time?

@MrNoyceCosta I don't there is a hard limit here (at least I couldn't find any in the documentation). However, please be careful to not have your GitHub Actions cost explode if you set the limit too high. You can also set the `task-wait-until-stopped` parameter to false to avoid having the GitHub Action wait for the task to finish. The Action will then simply start the action and return, not providing any log output or status.

**Comment by Ic3w0lf** [comment]
@gregnetau Hmm... this is weird! If you set `task-wait-until-stopped` to `false`, the action should exit immediatly after send the ECS command to AWS. The action should not print any log outputs of the container. Have you tried using the v4.1.0 release?

There was an issue in earlier versions using the SDKv3 that looked like yours, when the container that was started only ran for a short time. I explained that here in more detail: https://github.com/geekcell/github-action-aws-ecs-run-task/pull/29

Also, I assume its a copy-paste error, but make sure to not have the 3 backticks at the end of the `task-wait-until-stopped` parameter.

**Pull request merged**
